### ISSUE TITLE
debug report

### ISSUE THREAD

**Issue by swissk** [raffaem/pdfsak#20]
I keep getting errors when attempting to merge a directory. Can you, please advice what to do?

Thanks in advance,

pdfsak --debug --input-dir /home/daifu/Documents/Acupuncture/Scanned\ chinese\ medicine/output --output tcm_book.pdf
ERROR: unrecognized file type 'unknown' for '/home/daifu/Documents/Acupuncture/Scanned chinese medicine/output/temp/latex_file.log'

[report.zip](https://github.com/raffaem/pdfsak/files/12061203/report.zip)

**Comment by raffaem** [comment]
What error is it?

**Comment by swissk** [comment]
sudo apt-get install texlive-latex-extra fixed this issue.

Regards
