### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by GitHubRulesOK** [raffaem/pdfsak#8]
Just some doodles fell free to plagerise my plagarisms :-) or delete

![image](https://user-images.githubusercontent.com/12754913/149251516-e67c07c3-0151-4a69-b9a7-876c842a01d6.png)

**Comment by raffaem** [comment]
Hello,

Thank you very much, the one on the right looks good! :)

I'll wait and see the eventual proposals before choosing.

Thanks again!

**Comment by kgullion** [comment]
Quick shield logo inspired by the Victorinox logo.

![pdfsdk](https://user-images.githubusercontent.com/1663700/151039607-bee4d083-0fd6-4aa5-b87e-44aaf0f92de1.png)

Feel free to remix as you see fit.

[SVG version](https://user-images.githubusercontent.com/1663700/151039582-8c6d8d20-8b5c-4334-b261-ca36eb3defe5.svg)

**Comment by raffaem** [comment]
> Quick shield logo inspired by the Victorinox logo.
> 
> ![pdfsdk](https://user-images.githubusercontent.com/1663700/151039607-bee4d083-0fd6-4aa5-b87e-44aaf0f92de1.png)
> 
> Feel free to remix as you see fit.
> 
> [SVG version](https://user-images.githubusercontent.com/1663700/151039582-8c6d8d20-8b5c-4334-b261-ca36eb3defe5.svg)

Looks good, thanks!

**Comment by GitHubRulesOK** [comment]
Thats Odd JUST LIKE a pdf it depends on tour local fonts 
![image](https://user-images.githubusercontent.com/12754913/151072784-d1e731af-5641-43f3-82bc-0f1507477b5d.png)

**Comment by kgullion** [comment]
I used the "Open Sans" font originally, forgot to convert the text to a path though so if that font isn't installed it will render incorrectly. [Here](https://user-images.githubusercontent.com/1663700/151087356-c4fdb4f1-d012-4f6c-94e3-7ab854d77ad3.svg)'s one that doesn't depend on local fonts.

**Comment by GitHubRulesOK** [comment]
@kgullion Great and confirmed its sharp as a knife, however I liked the one with Swiss Helvetica :slightly_smiling_face: 
![image](https://user-images.githubusercontent.com/12754913/151088499-e743aa14-ea3f-4701-b48f-34f10be32269.png)

**Comment by raffaem** [comment]
> I used the "Open Sans" font originally, forgot to convert the text to a path though so if that font isn't installed it will render incorrectly. [Here](https://user-images.githubusercontent.com/1663700/151087356-c4fdb4f1-d012-4f6c-94e3-7ab854d77ad3.svg)'s one that doesn't depend on local fonts.

I will use that. Thank you very much!
